export const GET_ALL_TEMPLATES_REQUEST = 'GET_ALL_TEMPLATES_REQUEST';
export const GET_ALL_TEMPLATES_SUCCESS = 'GET_ALL_TEMPLATES_SUCCESS';
export const GET_ALL_TEMPLATES_FAIL = 'GET_ALL_TEMPLATES_FAIL';

export const GET_ALL_FILTERED_TEMPLATES = 'GET_ALL_FILTERED_TEMPLATES';
export const SET_TEMPLATE_HEADER = 'SET_TEMPLATE_HEADER';
